require "./remove_last_slash"
require "./route_parser"
require "./parse_cookie"
require "./parse_content_type"
# require "./json_result"
require "./get_class_name"
require "./async"
require "./get_view_from_file"
require "./negotiator"
require "./singleton"
require "./logger"
require "./instance"
